### ISSUE TITLE
Usher::Route#to should be able to take both app and options

### ISSUE THREAD

**Issue by botanicus** [joshbuddy/usher#3]
So I can put there default options which will be rewritten from `env`. See http://github.com/joshbuddy/usher/issues/#issue/2 for an example.

**Comment by joshbuddy** [comment]
I'd _really really_ like to avoid this. The "destination" should be literally what you pass it. Its up the destination to parse it. But, we could certainly wrap up multiple values passed to a destination into an array, and let the destination receiver unwrap it and do something with it. That'd make sense to me.

**Comment by joshbuddy** [comment]
Added a compound destination. This takes care of this.
