### ISSUE TITLE
get helper should handle HTTP HEAD as well

### ISSUE THREAD

**Issue by botanicus** [joshbuddy/usher#5]
I was trying to implement it in http://github.com/joshbuddy/usher/commit/c0365cb8e631db5870c10ccdfd1ed7f492b8e04b, but for some reason it doesn't work. It has test which are failing at the moment, can someone take a look at it please?

**Comment by joshbuddy** [comment]
Added support for arrays to be unpacked as request conditions

**Comment by botanicus** [comment]
Cheers, I'm going to try it ASAP!

**Comment by botanicus** [comment]
It works, thanks Josh!
