### ISSUE TITLE
Mach problem

### ISSUE THREAD

**Issue by DAddYE** [joshbuddy/usher#6]
Hi, 

I think there is a problem with matching routes see this sinatra example:

<pre>
      get("/my/:foo_id"){ params[:foo_id] }
      get("/my/:bar_id/bar"){ params[:bar_id] }
</pre>

Now my test:

<pre>
    get "/my/1"
    assert_equal "1", body
    get "/my/2/bar"
    assert_equal "2", body
</pre>

Result of second assert:

<pre>
<"2"> expected but was<"">.
</pre>

How we can resolve?

**Comment by joshbuddy** [comment]
This is fixed in 0.6.3.
