### ISSUE TITLE
gem install usher -> RDoc failure

### ISSUE THREAD

**Issue by hedgehog** [joshbuddy/usher#7]
<pre>
# gem install usher
Successfully installed usher-0.6.4
1 gem installed
Installing ri documentation for usher-0.6.4...

RDoc failure in lib/usher/util/mapper.rb at or around line 7 column 7

Before reporting this, could you check that the file
you're documenting compiles cleanly--RDoc is not a
full Ruby parser, and gets confused easily if fed
invalid programs.

The internal error was:

ERROR:  While executing gem ... (NoMethodError)
    undefined method `name' for #<RubyToken::TkNL:0x9a4811c @line_no=5, @text="\n", @char_no=10>
</pre>

**Comment by joshbuddy** [comment]
fixed in 0.6.5
